// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListDirectories():Promise<Array<string>>;

export function SelectDirectory():Promise<string>;

export function StopWatching():Promise<void>;

export function Watcher(arg1:string):Promise<void>;
